### PR TITLE
CMake: AppleClang support

### PR DESCRIPTION
**Pull request by rbange**
Same changes as in https://github.com/kit-parco/networkit/pull/212, but now resubmitted against Dev.

### CODE REVIEW

**Comment by avdgrinten** [comment]
I do not think the slightly increased complexity in CMakeLists.txt is hard to maintain. Not having to install a new compiler seems to be a real improvement for macOS users. Do you think the PR can be merged as-is or do you still want to change something?

**Comment by rbange** [comment]
From a technical point of view I have nothing to change, but for me there are still 2 open points:

1. Should we remove the compiler detection from the `setup.py`? It was initially introduced to tackle the problem of CMake + AppleClang
2. I think the travis script is expanding too hard. In contrast to Linux, it is quite common to work with the latest versions of compiler and programs on MacOS. I would recommend to remove the MacOS clang4 test and pump up the other MacOS test up to g++-8 instead of 6

**Comment by rbange** [comment]
PR is rebased to https://github.com/kit-parco/networkit/commit/07aceae5a180f2232c9f16eba700c2f0b718e465 (MSVC commit)

**Comment by avdgrinten** [comment]
Thanks for the rebase. Yes, the Travis script should be reduced, but that should be done in a different PR. The same applies for the compiler detection - but I am not entirely sure that we should remove that. I will accept the PR in this state (once the failing tests on Dev are fixed), IMHO it is a great improvement over the current state. Thank you for your work.

**Comment by rbange** [comment]
While looking into this PR, I realised that AppleClang would never be recognised by the determination function in `setup.py`. So if additional GNU or Clang compiler is installed, the installation would fail. The new commit first checks if a GNU/Clang compiler is installed and if not, tries to work with AppleClang.

So when I saw travis failing, I looked into the log and saw that the our own compiler identification never worked in the first place on travis. It just passed an empty "-DCMAKE_CXX_COMPILER=" flag and cmake fell back to the CXX environment variable. I don't know why the compiler identification fails on Travis, because I cannot recreate the bug. Nevertheless, i recreated the old behaviour in 
https://github.com/kit-parco/networkit/pull/217/commits/054b8ec17961e676188513abddca67b7cab5272 by using the CXX variable if it exists (which should be an expected behaviour - e.g. cmake and several other build systems do this by default)

btw Travis fails for MacOS+gcc6 build as trying to be fixed here: https://github.com/kit-parco/networkit/pull/229

**Comment by avdgrinten** [comment]
Maybe we should just use `NETWORKIT_OVERRIDE_CXX` in the Travis script then? Is there a need to support `CXX` and `NETWORKIT_OVERRRIDE_CXX` at the same time?

**Comment by avdgrinten** [comment]
Closing/reopening the commit to let Travis re-parse the configuration.

**Comment by avdgrinten** [comment]
One question is whether the new Travis configuration builds as intended. If it does, this PR can be merged.

**Comment by rbange** [comment]
> Maybe we should just use `NETWORKIT_OVERRIDE_CXX` in the Travis script then? Is there a need to support `CXX` and `NETWORKIT_OVERRRIDE_CXX` at the same time?

Well, I am not sure why we need a `NETWORKIT_OVERRRIDE_CXX` in the first place, because setting `CXX` should be the most common way to specify a compiler (e.g. also accepted by cmake). But yes, theoretically we could specify `NETWORKIT_OVERRRIDE_CXX` instead of `CXX` in Travis

**Comment by avdgrinten** [comment]
I thought we were already using `NETWORKIT_OVERRIDE_CXX` everywhere. Turns out that we do not; and it does not make sense anyway. I guess `NETWORKIT_OVERRIDE_CXX` can be removed.

This PR is ready to be merged. Let's wait for the CI to finish first, though.

**Comment by avdgrinten** [comment]
I am merging this. Thank you for your work, Roman.

**Pull request merged**
