### PR TITLE
MocnikGenerator: Code quality

### PR DESCRIPTION
**Pull request by mocnik-science**
This pull request improves code quality and running time.  I have also improved the (internal) documentation.  You previous comments have been very helpful.  If there are further comments that I should incorporate into the code, I would be happy to receive them.  Thank you!

### CODE REVIEW

**Comment by mocnik-science** [comment]
Sorry for having committed several bug fixes for the tests but I cannot get the tests running on my own hardware.  However, the tests work now as expected.

**Comment by avdgrinten** [comment]
Looks good. Just tell me when you're satisfied with the PR and I will merge it. If you want to get rid of the "unnecessary" commits you could rebase + force-push them; however, this is not strictly necessary to get the PR merged.

**Comment by mocnik-science** [comment]
Great to hear. In general, I am satisfied with the PR. It might happen that I have new insights of how to improve the code, but I do not expect it at the very moment. (I still do not understand completely why the algorithm does not become faster on 4 cores compared to 2 cores.) For me, it would be fine to just proceed with the commits as they are. If you prefer that I only create one commit, I would just clone again, copy the four files that I changed and commit again. Let me know what you prefer. – You see, I kept my promise to improve the code after the first merge!

**Comment by avdgrinten** [comment]
Yes, thank you. The code is in a good shape now, so I am merging this.

**Pull request merged**
