### PR TITLE
faster hasEdge() for undirected graphs

### PR DESCRIPTION
**Pull request by rbange**
As proposed by @michitux here #160, i implemented a more efficient hasEdge function. There is no reason this feature should be limited to Graph Readers alone so i applied the changes to the Graph.cpp itself.

Nevertheless, the changes do not really speed up the performance of graph readers, but are efficient in other use cases - especially under power law conditions. For example the LFRGenerator uses the hasEdge method very extensively. I benchmarked the generation of a graph with power law degrees and recognized performance increases of around 10%.

### CODE REVIEW

**Comment by rbange** [comment]
BTW the build works. Travis fails in its last attempt by at downloading ( `brew install llvm37`) for whatever reason? Is there a way to restart Travis?

**Comment by kolja-esders** [comment]
I manually restarted the job. Seems to be a temporary network issue.

**Comment by michitux** [comment]
This could also be implemented for directed graphs by using the in-degree and `indexInInEdgeArray`.

**Comment by rbange** [comment]
I conducted the changes and made use of `indexInInArray`, but then the test suite failed.
After conducting several tests on my own, I looked up the failing tests and i'm still not sure why this test passed in the first place for directed graphs, because nodes were swapped.

There might be a problem at the GraphBuilder in matching half edges!? (error was not recognised because only `indexInOutArray` was used)

**Pull request merged**
