### PR TITLE
Fix tabs in SConstruct

### LINKED ISSUE #101: Messed up tabs and spaces on line 71 of SConstruct
There should be 4 more spaces on line 71

### PR DESCRIPTION
**Pull request by kolja-esders**
Resolves #101.

### CODE REVIEW

**Comment by avdgrinten** [comment]
I rebased the patch onto Dev (careful, this was force-pushed) and added a commit to turn the spaces/tabs mess in SConstruct into all tabs.

Can we merge this?

**Comment by hmeyerhenke** [comment]
As a general remark: Please avoid forced pushes whenever possible. (I guess you had a good reason.)

**Comment by avdgrinten** [comment]
The Travis failure here is resolved by #108.

@hmeyerhenke Yes, we will never force push into one of the "public" branches (master and Dev). Force pushing to update pull requests (i.e. pushing to private feature/fix branches) should be fine though, as long as other people are informed (e.g. as a comment to the pull request).

**Comment by avdgrinten** [comment]
@kolja-esders This patch seems to be complete. Can I tidy up the branch and merge or is there anything left to do?

**Comment by kolja-esders** [comment]
Should be ready to go.

**Pull request merged**
